GET http://localhost:8080/ddd-poc/ws/agregadores/
###

GET http://localhost:8080/ddd-poc/ws/agregadores/{id}
###

POST http://localhost:8080/ddd-poc/ws/agregadores/
###

POST http://localhost:8080/ddd-poc/ws/agregadores/{id}/entidades/

entidade
###

POST http://localhost:8080/ddd-poc/ws/agregadores/{id}/objetos/

objeto
###

DELETE http://localhost:8080/ddd-poc/ws/agregadores/{id}
###
